### ISSUE TITLE
Search broken because app is blocked by Algolia

### ISSUE THREAD

**Issue by ubersan** [python-poetry/website#122]
It seems that something is wrong with the algolia account. Requests to the provider return `403`:

```json
{
    "message": "This operation cannot be processed, the application is blocked. Contact us to unblock it.",
    "status": 403
}
```

This of course results in the search not working as no search results are available

![image](https://github.com/python-poetry/website/assets/60277151/dc4c84d9-f492-4312-84b5-3d7031e4736c)

**Comment by branchvincent** [comment]
I think we had reached our free tier limit with Algolia, but should be fixed now. Let us know if you see it again
