### ISSUE TITLE
Production website not working

### ISSUE THREAD

**Issue by MRichards99** [python-poetry/website#127]
https://python-poetry.org/ doesn't seem to be working today, I'm getting timeouts on multiple devices.

Just thought I'd create an issue so someone's aware of the situation.

**Comment by Secrus** [comment]
It loads fine for me. It's probably an issue on your end. I had multiple people test it and it works on Apple devices, Linux and Windows.

**Comment by MRichards99** [comment]
Ah yes, it does appear to be something on our end - apologies for the incorrect information.
