### ISSUE TITLE
current version?

### ISSUE THREAD

**Issue by henning** [python-poetry/website#69]
I want to get started with poetry, but I am unsure which is the current version.
The website offers docs for master, 1.1 and 1.2 in one part, without saying something about the state of each.

In another part it says 1.1 is "stable" and "master" is development, but not what 1.2 is.

Digging a bit deeper 1.2 seems to be on the way to be released, or is it already? 

Can someone explain/help me? Thanks in advance!

**Comment by henning** [comment]
Also: when i run the install command described on the website for Version 1.2 (from URL https://python-poetry.org/docs/1.2/):

curl -sSL https://install.python-poetry.org | python3 -

I get poetry version 1.1.5 installed.

**Comment by finswimmer** [comment]
The current stable version is 1.1.15. This is why the default documentation link to 1.1.

For Poetry 1.2 there is a release candidate and if no blocking issue arise, the final version will be released next week.
